apiVersion: policy.karmada.io/v1alpha1
kind: PropagationPolicy
metadata:
 name: hello-propagation
spec:
 propagateDeps: true
 resourceSelectors:
   - apiVersion: apps/v1
     kind: Deployment
   - apiVersion: v1
     kind: Service
 placement:
   clusterAffinity:
     clusterNames:
       - us
       - uk
   replicaScheduling:
     replicaDivisionPreference: Weighted
     replicaSchedulingType: Divided
     weightPreference:
       staticWeightList:
         - targetCluster:
             clusterNames:
               - us
                 uk
           weight: 1
